// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FilePoller.Entities;

public partial class Jobs
{
    public int Id { get; set; }

    public Guid JobId { get; set; }

    public DateTime StartDateTime { get; set; }

    public DateTime? StopDateTime { get; set; }

    public string JobUser { get; set; }
}