// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FilePoller.Entities;

public partial class StatementAutomationContext : DbContext
{
    private IConfiguration _configuration;

    public StatementAutomationContext(IConfiguration configuration)
    {
        _configuration = configuration;
    }
    public StatementAutomationContext(DbContextOptions<StatementAutomationContext> options, IConfiguration configuration)
        : base(options)
    {
        _configuration = configuration;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (optionsBuilder.IsConfigured) return;

        optionsBuilder.UseSqlServer(_configuration.GetSection("ConnectionStrings").GetSection("DataConnection").Value);

    }

    public virtual DbSet<Directories> Directories { get; set; }

    public virtual DbSet<JobSteps> JobSteps { get; set; }

    public virtual DbSet<Jobs> Jobs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Directories>(entity =>
        {
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UncPath)
                .IsRequired()
                .HasMaxLength(2000);
        });

        modelBuilder.Entity<JobSteps>(entity =>
        {
            entity.Property(e => e.StepDate).HasDefaultValueSql("(getdate())", "DF_JobSteps_StepDate");
            entity.Property(e => e.StepValue)
                .IsRequired()
                .HasMaxLength(1000);
        });

        modelBuilder.Entity<Jobs>(entity =>
        {
            entity.Property(e => e.JobUser)
                .IsRequired()
                .HasMaxLength(20);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}