// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StatementProcessorApi.Entities;

public partial class ProcessObjects
{
    public int Id { get; set; }

    public Guid JobId { get; set; }

    public string FileDirName { get; set; }

    public bool IsZip { get; set; }

    public bool IsFile { get; set; }
}