// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StatementProcessorApi.Entities;

public partial class Services
{
    public int Id { get; set; }

    public string ServiceName { get; set; }

    public string ServerName { get; set; }
}