// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace StatementProcessorApi.Entities;

public partial class StatementAutomationContext : DbContext
{
    public StatementAutomationContext(DbContextOptions<StatementAutomationContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Directories> Directories { get; set; }

    public virtual DbSet<JobSteps> JobSteps { get; set; }

    public virtual DbSet<Jobs> Jobs { get; set; }

    public virtual DbSet<ProcessObjects> ProcessObjects { get; set; }

    public virtual DbSet<Services> Services { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Directories>(entity =>
        {
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UncPath)
                .IsRequired()
                .HasMaxLength(2000);
        });

        modelBuilder.Entity<JobSteps>(entity =>
        {
            entity.Property(e => e.StepDate).HasDefaultValueSql("(getdate())", "DF_JobSteps_StepDate");
            entity.Property(e => e.StepValue)
                .IsRequired()
                .HasMaxLength(1000);
        });

        modelBuilder.Entity<Jobs>(entity =>
        {
            entity.Property(e => e.JobUser)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<ProcessObjects>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_StatementFiles");

            entity.Property(e => e.FileDirName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Services>(entity =>
        {
            entity.Property(e => e.ServerName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ServiceName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}