// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Compressor.Entities;

public partial class CompressionLogs
{
    public int Id { get; set; }

    public Guid JobId { get; set; }

    public string FileName { get; set; }

    public long FileSize { get; set; }

    public DateOnly CompressDate { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly? StopTime { get; set; }

    public string CompressedFileName { get; set; }

    public long? CompressedFileSize { get; set; }

    public string Arguments { get; set; }
}