// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Compressor.Entities;

public partial class Directories
{
    public int Id { get; set; }

    public string UncPath { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }
}