// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Compressor.Entities;

public partial class JobSteps
{
    public int Id { get; set; }

    public Guid JobId { get; set; }

    public string StepValue { get; set; }

    public DateTime StepDate { get; set; }
}